### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by lorenzoa7** [alyssapiresfernandescefet/charactersheet#4]
Olá, sou mestre de um RPG com arte totalmente original, em live, chamado Juízo Divino (insta: @juizodivino) e estou construindo a segunda temporada agora. Gostaria de usar um sistema integrado com OBS com automatização de funções, como o do Ordem Paranormal e preciso muito de uma ajuda de quem já mexeu com fichas. Vi que você é extremamente talentosa e gostaria de entrar em contato com você. Meu twitter é @lorenzoaceti_   e meu instagram é  @lorenzoacetii  , se puder me mandar uma mensagem por uma dessas redes, estarei muito agradecido!

Sucesso pelo seu projeto!

**Comment by lunapiresfernandescefet** [comment]
Te mandei uma mensagem lá no Twitter!
