### ISSUE TITLE
me ajuda. Hospedagem

### ISSUE THREAD

**Issue by ikui123** [alyssapiresfernandescefet/charactersheet#5]
Sei que parece tarde e meu pedido ser um pouco estranho, mas vamos lá.

Eu quero mestrar um rpg, só que esse rpg possui sistemas e outras coisas diferentes, então dei fork na ficha pq achei bem legal e pá. Mas quando eu fui usar o heroku pra hospedar, eu estou tentando usar o db4free como database, como dito no tutorial do over(tutorial q estou usando para aprender a hospedar video, ele é o cara q faz a progamação do rpg do cellbit la e pá.) 

Resumindo, no video ele usa outro sistema, e la a hospedagem é outra, então gostaria de que me ajudasse a como eu poderia hospedar a ficha em algum lugar, sério, imploro. Quer dizer, se vc me deixa fazer isso primeiramente. Espero que sim, já que apenas quero mudar os status e as pericias dos jogadores, e nada mas.

**Comment by ikui123** [comment]
Mudança.

Consegui hospedar, eu acho, mas na hora do login eu não consigo regristrar nem acessar. Mesmo botando o usuario, senha e etc que botei no heroku

**Comment by alyssapiresfernandescefet** [comment]
Me manda uma mensagem no discord!
That Alyssa #0615
